services:
    app:
        build: .
        ports:
            - '8080:8080'
        volumes:
            - .:/app
        environment:
            - NODE_ENV=development
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=app_development
            - DB_HOST=db
        command: npm run watch
        depends_on:
            db:
                condition: service_healthy

    db:
        image: postgres:17
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=app_development
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 5s
            timeout: 5s
            retries: 5

volumes:
    postgres_data:
